### ISSUE TITLE
Add support for pagination parameters in search dependents query

### ISSUE THREAD

**Issue by tankakatan** [SporkHubr/Spork-go#28]
I need to request a particular page number and size when making a `searchDependents` call.

Ideally I'd like to be able to determine if the returned chunk of data represents the last page of the dependent list. For instance, if there are 92 dependents in total and I request `{ pageNumber: 2, pageSize: 50 }` (providing the page indexation starts from 1), the response should be something like `{ data: [ /* dependents */ ], count: 42, isLastPage: true }`.

If no pagination parameters provided within a request, the first page of a default size to be returned.

**Comment by JackBekket** [comment]
@tankakatan Я обнаружил здесь некоторую магию с рейт лимитом

1. Он считает запросами поисковые запросы с любым объемом
2. Пагинация и объем страниц задаются для поискового запроса
3. Рейт лимит на поисковые запросы у меня - 30 в минуту, но не всегда срабатывает в нужный момент.. это значит, что в минуту можно искать не более чем по 30 зависимостям одновременно


Что я сделал 

1.добавил пагинацию в запрос, как ты просил
2.добавил проверку хит лимита в процессе цепочки поисковых запросов, теперь search dependents не возвращает ошибку, но возвращает тот массив, который успел получить до наступления хит лимита, а так же флаг, сигнализирующий, что мы врезались в стенку
3. основная функция поиска searchDependentsArray, осуществляющая поиск по всему массиву, так же возвращает флаг, если на мы врезались 
4. в ту же основную функцию добавил фильтр поиска onlyEmail, который отфильтровывает найденных пользователей, отбрасывая людей без контактов

Что еще можно улучшить 
В рейт лимит мы упираемся от количества запросов, но не их объема
Если мы увеличим количество результатов на одну страницу поиска, то мы сможем обрабатывать большее количество найденных программистов и увеличить рейт лимит

Еще фронт может отлавливать, что наступил хит лимит и в следующий раз начинать загрузку новой страницы с прошлого места остановки, но это не имеет особого смысла кажется :/
