### ISSUE TITLE
Add filters for search dependents query response

### ISSUE THREAD

**Issue by tankakatan** [SporkHubr/Spork-go#29]
If possible I would like to be able to filter the `searchDependents` response. The filter should pick the dependents who have a desired attribute value or omit the ones who have an undesired attribute value. For instance, I'd like to request only dependents whose `Email` is not an empty string.

Given the fact that the response is paginated, the filtering should be implemented only by the leverage of the GitHub API. I.e. **the filtering should not happen within the `searchDependents` itself**. Otherwise a client may find himself iterating through the pages of no data, which makes absolutely no sense.

**Comment by JackBekket** [comment]
@tankakatan готово
